name: "Sample Validation"

on:
  pull_request:

jobs:
  check_definitions:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: "Install dependencies"
        run: npm install ajv@8.12.0

      - name: "Validate sample definition files"
        run: node .github/supporting-files/validate-sample-definitions.js
